In [41]:
import numpy as np
import pandas as pd

In [42]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [43]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [44]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [45]:
movies = movies.merge(credits,on = 'title')

In [46]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [47]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [48]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [49]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [50]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [51]:
movies.dropna(inplace=True)

In [52]:
movies.duplicated().sum()

0

In [53]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [54]:
def convert(obj):   #helper function to help retreive the genre name from the list of dictionaries obtained
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

In [15]:
movies['genres'] = movies['genres'].apply(convert)

NameError: name 'ast' is not defined

In [16]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [56]:
movies['keywords'] = movies['keywords'].apply(convert)

In [55]:
import ast

In [19]:
def convert3(obj):   
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [57]:
movies['cast'] = movies['cast'].apply(convert3)

In [21]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [39]:
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

In [58]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [24]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [25]:
movies.overview[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [26]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [27]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [28]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""..."

In [30]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [31]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 1, 4, 6, 3, ,, , "", n,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, 4, 2...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[[, {, "", i, d, "", :, , 1, 2, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 2, 7, 0, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 4, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 4, 7, 0, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 1, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 4, 9, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 2, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[[, {, "", i, d, "", :, , 2, 8, ,, , "", n, a, m,...","[[, {, "", i, d, "", :, , 8, 1, 8, ,, , "", n, a,...","[[, {, "", c, a, s, t, _, i, d, "", :, , 5, ,, ,...","[[, {, "", c, r, e, d, i, t, _, i, d, "", :, , ""...","[John, Carter, is, a, war-weary,, former, mili..."

In [32]:
new_df = movies[['movie_id','title','tags']]

In [33]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

/var/folders/3n/j_8csc016vb0b5n5722wdb8c0000gn/T/ipykernel_15491/1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [34]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

/var/folders/3n/j_8csc016vb0b5n5722wdb8c0000gn/T/ipykernel_15491/1380776331.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

In [37]:
from sklearn.feature_extraction.text import CountVectorizer     #to help vectorize the text using 'bag of words' method
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [35]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (1.1.2)
Requirement already satisfied: joblib>=1.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-learn) (1.0.1)
Requirement already satisfied: numpy>=1.17.3 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-learn) (1.20.3)
Requirement already satisfied: threadpoolctl>=2.0.0 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: scipy>=1.3.2 in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from scikit-learn) (1.7.3)
Note: you may need to restart the kernel to use updated packages.

In [72]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000, stop_words = 'english')

In [77]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [78]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [81]:
pip install nltk

Requirement already satisfied: nltk in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (3.6.2)
Requirement already satisfied: click in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nltk) (8.0.0)
Requirement already satisfied: tqdm in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nltk) (4.60.0)
Requirement already satisfied: joblib in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nltk) (1.0.1)
Requirement already satisfied: regex in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (from nltk) (2021.4.4)
Note: you may need to restart the kernel to use updated packages.

In [82]:
import nltk

In [83]:
from nltk.stem.porter import PorterStemmer   # We have to 'stem' our 'tags' column, so, all alike words merge into the same word
ps = PorterStemmer()

In [84]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
        
    return " ".join(y)

In [85]:
new_df['tags'] = new_df['tags'].apply(stem)   #Converted all words with the same meaning (example plurals,continuous tense,etc.) into one common word

/var/folders/3n/j_8csc016vb0b5n5722wdb8c0000gn/T/ipykernel_7873/3213734980.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [86]:
from sklearn.metrics.pairwise import cosine_similarity

In [88]:
similarity = cosine_similarity(vectors)        #calculates the percentage similarity between elements using to the cosine distance between vectors
#Note: The closer the similarity is to 1, the more similar it is and vice-versa

In [105]:
def recommend(movie):
    movie_index = new_df[new_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(new_df.iloc[i[0]].title)

In [107]:
recommend('Batman Begins')

The Dark Knight
The Dark Knight Rises
Batman
Batman & Robin
Batman

In [94]:
new_df.iloc[1216]

movie_id                                                  440
title                             Aliens vs Predator: Requiem
tags        a sequel to 2004' alien vs. predator, the icon...
Name: 1216, dtype: object

In [101]:
new_df[new_df['title'] == 'Batman Begins'].index[0]

119

In [104]:
sorted(list(enumerate(similarity[1])))

[(0, 0.08964214570007951),
 (1, 0.9999999999999999),
 (2, 0.062499999999999986),
 (3, 0.020833333333333332),
 (4, 0.08183170883849714),
 (5, 0.12376844287208427),
 (6, 0.0236227795630767),
 (7, 0.13176156917368248),
 (8, 0.06454972243679027),
 (9, 0.0799502686333539),
 (10, 0.09231861823449955),
 (11, 0.05661385170722978),
 (12, 0.4342995181076895),
 (13, 0.09901475429766741),
 (14, 0.11952286093343935),
 (15, 0.0799502686333539),
 (16, 0.08603090020146065),
 (17, 0.26940795304016235),
 (18, 0.0472455591261534),
 (19, 0.11410886614690958),
 (20, 0.08111071056538126),
 (21, 0.06681531047810609),
 (22, 0.07372097807744857),
 (23, 0.10022296571715913),
 (24, 0.14731391274719738),
 (25, 0.11437392774945347),
 (26, 0.11952286093343935),
 (27, 0.07426106572325056),
 (28, 0.06565321642986127),
 (29, 0.04950737714883371),
 (30, 0.1275775907699572),
 (31, 0.10206207261596575),
 (32, 0.09534625892455922),
 (33, 0.10825317547305485),
 (34, 0.036084391824351615),
 (35, 0.10825317547305485),
 (36, 0.0828236445561349),
 (37, 0.05892556509887895),
 (38, 0.10963225241337865),
 (39, 0.06154574548966637),
 (40, 0.05892556509887895),
 (41, 0.07654655446197431),
 (42, 0.0),
 (43, 0.05103103630798288),
 (44, 0.041666666666666664),
 (45, 0.07150969419341942),
 (46, 0.12309149097933274),
 (47, 0.09053574604251853),
 (48, 0.0944911182523068),
 (49, 0.03340765523905304),
 (50, 0.09525009525014289),
 (51, 0.045267873021259265),
 (52, 0.08718572905786445),
 (53, 0.052128603514268686),
 (54, 0.036860489038724284),
 (55, 0.08219949365267865),
 (56, 0.0753778361444409),
 (57, 0.09095085938862485),
 (58, 0.073543550676819),
 (59, 0.10489766978708612),
 (60, 0.0),
 (61, 0.1543033499620919),
 (62, 0.12862393885688161),
 (63, 0.04811252243246881),
 (64, 0.032826608214930636),
 (65, 0.02192645048267573),
 (66, 0.13032150878567172),
 (67, 0.062499999999999986),
 (68, 0.10606601717798213),
 (69, 0.054410718758250876),
 (70, 0.06063390625908323),
 (71, 0.11322770341445956),
 (72, 0.09682458365518541),
 (73, 0.03857583749052298),
 (74, 0.026352313834736494),
 (75, 0.19050019050028574),
 (76, 0.053916386601719206),
 (77, 0.04651302547095317),
 (78, 0.053916386601719206),
 (79, 0.11043152607484653),
 (80, 0.036084391824351615),
 (81, 0.08164965809277258),
 (82, 0.029061909685954818),
 (83, 0.0773565934694095),
 (84, 0.10879853497231112),
 (85, 0.11118739749916517),
 (86, 0.06154574548966637),
 (87, 0.030316953129541614),
 (88, 0.09525009525014289),
 (89, 0.032009219983223994),
 (90, 0.10206207261596575),
 (91, 0.10022296571715913),
 (92, 0.073543550676819),
 (93, 0.053300179088902604),
 (94, 0.1386750490563073),
 (95, 0.026064301757134343),
 (96, 0.09374999999999997),
 (97, 0.07819290527140303),
 (98, 0.15875015875023812),
 (99, 0.06154574548966637),
 (100, 0.03857583749052298),
 (101, 0.06154574548966637),
 (102, 0.04682929057908469),
 (103, 0.09205746178983235),
 (104, 0.15624999999999994),
 (105, 0.11306675421666135),
 (106, 0.11707322644771173),
 (107, 0.07216878364870322),
 (108, 0.05050762722761053),
 (109, 0.16666666666666666),
 (110, 0.025785531156469834),
 (111, 0.06350006350009525),
 (112, 0.06454972243679027),
 (113, 0.05455447255899809),
 (114, 0.053916386601719206),
 (115, 0.11624763874381927),
 (116, 0.029880715233359837),
 (117, 0.09525009525014289),
 (118, 0.018430244519362142),
 (119, 0.05050762722761053),
 (120, 0.0),
 (121, 0.09525009525014289),
 (122, 0.13608276348795434),
 (123, 0.05157106231293967),
 (124, 0.07086833868923009),
 (125, 0.033557802760701215),
 (126, 0.12126781251816646),
 (127, 0.10206207261596573),
 (128, 0.032826608214930636),
 (129, 0.1656472891122698),
 (130, 0.03340765523905304),
 (131, 0.08838834764831843),
 (132, 0.07426106572325056),
 (133, 0.07071067811865475),
 (134, 0.07071067811865475),
 (135, 0.0),
 (136, 0.0799502686333539),
 (137, 0.018042195912175808),
 (138, 0.1453095484297741),
 (139, 0.09128709291752767),
 (140, 0.026650089544451302),
 (141, 0.04055535528269063),
 (142, 0.10400628679223047),
 (143, 0.12141073279465803),
 (144, 0.058123819371909635),
 (145, 0.0472455591261534),
 (146, 0.018233123937236816),
 (147, 0.06565321642986127),
 (148, 0.07372097807744857),
 (149, 0.06735198826004057),
 (150, 0.08838834764831843),
 (151, 0.08333333333333333),
 (152, 0.06681531047810609),
 (153, 0.04490132550669372),
 (154, 0.03466876226407682),
 (155, 0.0),
 (156, 0.04682929057908469),
 (157, 0.07372097807744857),
 (158, 0.0799502686333539),
 (159, 0.07071067811865475),
 (160, 0.060048057676907664),
 (161, 0.036860489038724284),
 (162, 0.07715167498104596),
 (163, 0.027607881518711633),
 (164, 0.09682458365518541),
 (165, 0.026352313834736494),
 (166, 0.062499999999999986),
 (167, 0.10606601717798213),
 (168, 0.11180339887498948),
 (169, 0.09999999999999999),
 (170, 0.04811252243246881),
 (171, 0.12499999999999997),
 (172, 0.07905694150420947),
 (173, 0.026064301757134343),
 (174, 0.058123819371909635),
 (175, 0.053916386601719206),
 (176, 0.06454972243679027),
 (177, 0.0),
 (178, 0.0808745799025788),
 (179, 0.04055535528269063),
 (180, 0.024056261216234404),
 (181, 0.049029033784546004),
 (182, 0.08492077756084468),
 (183, 0.05856516070822727),
 (184, 0.05455447255899809),
 (185, 0.029061909685954818),
 (186, 0.042257712736425826),
 (187, 0.20623947784607635),
 (188, 0.023836564731139806),
 (189, 0.042874646285627205),
 (190, 0.15348515337873012),
 (191, 0.10660035817780521),
 (192, 0.026064301757134343),
 (193, 0.11507182723729042),
 (194, 0.0),
 (195, 0.06804138174397717),
 (196, 0.06063390625908323),
 (197, 0.075),
 (198, 0.062499999999999986),
 (199, 0.2671036121482476),
 (200, 0.041666666666666664),
 (201, 0.0),
 (202, 0.036084391824351615),
 (203, 0.06154574548966637),
 (204, 0.026958193300859603),
 (205, 0.08333333333333333),
 (206, 0.09901475429766741),
 (207, 0.059761430466719674),
 (208, 0.13258252147247765),
 (209, 0.07905694150420947),
 (210, 0.057353933467640436),
 (211, 0.02830692585361489),
 (212, 0.053300179088902604),
 (213, 0.045267873021259265),
 (214, 0.062499999999999986),
 (215, 0.10206207261596575),
 (216, 0.2041241452319315),
 (217, 0.07150969419341942),
 (218, 0.044194173824159216),
 (219, 0.06933752452815364),
 (220, 0.09847982464479191),
 (221, 0.025785531156469834),
 (222, 0.0944911182523068),
 (223, 0.058123819371909635),
 (224, 0.022097086912079608),
 (225, 0.05521576303742327),
 (226, 0.062499999999999986),
 (227, 0.06454972243679027),
 (228, 0.0799502686333539),
 (229, 0.04055535528269063),
 (230, 0.04351941398892445),
 (231, 0.0),
 (232, 0.12499999999999997),
 (233, 0.07372097807744857),
 (234, 0.0944911182523068),
 (235, 0.062499999999999986),
 (236, 0.03340765523905304),
 (237, 0.07216878364870323),
 (238, 0.06681531047810609),
 (239, 0.02321191727213148),
 (240, 0.0799502686333539),
 (241, 0.09374999999999997),
 (242, 0.09847982464479191),
 (243, 0.07819290527140303),
 (244, 0.032826608214930636),
 (245, 0.06350006350009525),
 (246, 0.06904309634237427),
 (247, 0.036084391824351615),
 (248, 0.04950737714883371),
 (249, 0.0753778361444409),
 (250, 0.03768891807222045),
 (251, 0.0),
 (252, 0.04767312946227961),
 (253, 0.0472455591261534),
 (254, 0.057353933467640436),
 (255, 0.029061909685954818),
 (256, 0.042874646285627205),
 (257, 0.059761430466719674),
 (258, 0.024514516892273002),
 (259, 0.06681531047810609),
 (260, 0.09847982464479191),
 (261, 0.026650089544451302),
 (262, 0.10206207261596575),
 (263, 0.11058146711617285),
 (264, 0.0),
 (265, 0.030772872744833184),
 (266, 0.029061909685954818),
 (267, 0.11306675421666135),
 (268, 0.028676966733820218),
 (269, 0.0),
 (270, 0.0808745799025788),
 (271, 0.11043152607484653),
 (272, 0.0),
 (273, 0.07576144084141578),
 (274, 0.033864273073929814),
 (275, 0.032826608214930636),
 (276, 0.1386750490563073),
 (277, 0.04602873089491617),
 (278, 0.053916386601719206),
 (279, 0.026958193300859603),
 (280, 0.06154574548966637),
 (281, 0.02551551815399144),
 (282, 0.03227486121839514),
 (283, 0.030316953129541614),
 (284, 0.02128141326896871),
 (285, 0.04767312946227961),
 (286, 0.07086833868923009),
 (287, 0.028676966733820218),
 (288, 0.0),
 (289, 0.05270462766947299),
 (290, 0.06933752452815364),
 (291, 0.05892556509887895),
 (292, 0.10606601717798213),
 (293, 0.03340765523905304),
 (294, 0.09374999999999997),
 (295, 0.057353933467640436),
 (296, 0.043193421279068),
 (297, 0.02551551815399144),
 (298, 0.0),
 (299, 0.043193421279068),
 (300, 0.05521576303742327),
 (301, 0.02128141326896871),
 (302, 0.062499999999999986),
 (303, 0.030316953129541614),
 (304, 0.0753778361444409),
 (305, 0.06735198826004057),
 (306, 0.032826608214930636),
 (307, 0.03646624787447363),
 (308, 0.036860489038724284),
 (309, 0.06933752452815364),
 (310, 0.17057205980525325),
 (311, 0.027277236279499045),
 (312, 0.08718572905786445),
 (313, 0.0),
 (314, 0.0),
 (315, 0.09525009525014289),
 (316, 0.023414645289542346),
 (317, 0.0),
 (318, 0.0),
 (319, 0.03768891807222045),
 (320, 0.035355339059327376),
 (321, 0.0),
 (322, 0.08718572905786445),
 (323, 0.034020690871988585),
 (324, 0.027607881518711633),
 (325, 0.11858541225631421),
 (326, 0.031249999999999993),
 (327, 0.06154574548966637),
 (328, 0.03227486121839514),
 (329, 0.11624763874381927),
 (330, 0.1178511301977579),
 (331, 0.052128603514268686),
 (332, 0.09095085938862485),
 (333, 0.03227486121839514),
 (334, 0.11180339887498948),
 (335, 0.029061909685954818),
 (336, 0.07715167498104596),
 (337, 0.025253813613805264),
 (338, 0.0),
 (339, 0.059761430466719674),
 (340, 0.1656472891122698),
 (341, 0.06454972243679027),
 (342, 0.10206207261596573),
 (343, 0.0),
 (344, 0.032826608214930636),
 (345, 0.04950737714883371),
 (346, 0.0),
 (347, 0.0),
 (348, 0.07071067811865475),
 (349, 0.16137430609197567),
 (350, 0.057353933467640436),
 (351, 0.0),
 (352, 0.062499999999999986),
 (353, 0.024999999999999998),
 (354, 0.0),
 (355, 0.0625),
 (356, 0.06350006350009525),
 (357, 0.0),
 (358, 0.034020690871988585),
 (359, 0.10825317547305485),
 (360, 0.0),
 (361, 0.059761430466719674),
 (362, 0.034020690871988585),
 (363, 0.04767312946227961),
 (364, 0.05455447255899809),
 (365, 0.0),
 (366, 0.031249999999999993),
 (367, 0.0),
 (368, 0.07071067811865475),
 (369, 0.09682458365518541),
 (370, 0.05892556509887895),
 (371, 0.053916386601719206),
 (372, 0.02795084971874737),
 (373, 0.0),
 (374, 0.06904309634237427),
 (375, 0.022633936510629633),
 (376, 0.05103103630798288),
 (377, 0.0),
 (378, 0.03340765523905304),
 (379, 0.055901699437494734),
 (380, 0.0),
 (381, 0.0944911182523068),
 (382, 0.0),
 (383, 0.053916386601719206),
 (384, 0.06804138174397717),
 (385, 0.032826608214930636),
 (386, 0.07284643967679481),
 (387, 0.02830692585361489),
 (388, 0.02795084971874737),
 (389, 0.1386750490563073),
 (390, 0.029880715233359837),
 (391, 0.04256282653793742),
 (392, 0.09847982464479191),
 (393, 0.029462782549439476),
 (394, 0.027277236279499045),
 (395, 0.0),
 (396, 0.024514516892273002),
 (397, 0.029061909685954818),
 (398, 0.05270462766947299),
 (399, 0.026958193300859603),
 (400, 0.07216878364870323),
 (401, 0.0),
 (402, 0.06565321642986127),
 (403, 0.13927150363278887),
 (404, 0.0),
 (405, 0.03227486121839514),
 (406, 0.0),
 (407, 0.053916386601719206),
 (408, 0.03857583749052298),
 (409, 0.036084391824351615),
 (410, 0.05270462766947299),
 (411, 0.09095085938862485),
 (412, 0.134790966504298),
 (413, 0.058123819371909635),
 (414, 0.03466876226407682),
 (415, 0.01853123291652753),
 (416, 0.05892556509887895),
 (417, 0.036084391824351615),
 (418, 0.039528470752104736),
 (419, 0.0799502686333539),
 (420, 0.10783277320343841),
 (421, 0.0),
 (422, 0.03857583749052298),
 (423, 0.053916386601719206),
 (424, 0.04256282653793742),
 (425, 0.04950737714883371),
 (426, 0.064790131918602),
 (427, 0.03227486121839514),
 (428, 0.041666666666666664),
 (429, 0.0),
 (430, 0.0),
 (431, 0.053916386601719206),
 (432, 0.05270462766947299),
 (433, 0.03466876226407682),
 (434, 0.028676966733820218),
 (435, 0.08333333333333333),
 (436, 0.0),
 (437, 0.06063390625908323),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.025253813613805264),
 (443, 0.06154574548966637),
 (444, 0.026650089544451302),
 (445, 0.0),
 (446, 0.026958193300859603),
 (447, 0.024999999999999998),
 (448, 0.053916386601719206),
 (449, 0.030772872744833184),
 (450, 0.0),
 (451, 0.027277236279499045),
 (452, 0.03340765523905304),
 (453, 0.02795084971874737),
 (454, 0.026064301757134343),
 (455, 0.025785531156469834),
 (456, 0.024514516892273002),
 (457, 0.09231861823449955),
 (458, 0.024753688574416854),
 (459, 0.03768891807222045),
 (460, 0.0),
 (461, 0.11306675421666135),
 (462, 0.0206901472150592),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.07372097807744857),
 (467, 0.07216878364870322),
 (468, 0.06350006350009525),
 (469, 0.049029033784546004),
 (470, 0.05157106231293967),
 (471, 0.11624763874381927),
 (472, 0.1178511301977579),
 (473, 0.053300179088902604),
 (474, 0.0),
 (475, 0.07150969419341942),
 (476, 0.03768891807222045),
 (477, 0.0),
 (478, 0.042257712736425826),
 (479, 0.0397778642087865),
 (480, 0.05455447255899809),
 (481, 0.0),
 (482, 0.0),
 (483, 0.10206207261596575),
 (484, 0.036084391824351615),
 (485, 0.059761430466719674),
 (486, 0.10206207261596573),
 (487, 0.07372097807744857),
 (488, 0.040032038451271776),
 (489, 0.041666666666666664),
 (490, 0.07905694150420947),
 (491, 0.04767312946227961),
 (492, 0.06565321642986127),
 (493, 0.04082482904638629),
 (494, 0.0),
 (495, 0.0753778361444409),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0753778361444409),
 (499, 0.031750031750047626),
 (500, 0.029061909685954818),
 (501, 0.06904309634237427),
 (502, 0.026650089544451302),
 (503, 0.08838834764831843),
 (504, 0.035355339059327376),
 (505, 0.07715167498104596),
 (506, 0.0),
 (507, 0.07216878364870322),
 (508, 0.12126781251816646),
 (509, 0.0808745799025788),
 (510, 0.027607881518711633),
 (511, 0.10022296571715913),
 (512, 0.031750031750047626),
 (513, 0.06154574548966637),
 (514, 0.09374999999999997),
 (515, 0.0),
 (516, 0.0),
 (517, 0.022821773229381916),
 (518, 0.057353933467640436),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.05455447255899809),
 (524, 0.034020690871988585),
 (525, 0.026064301757134343),
 (526, 0.0),
 (527, 0.0),
 (528, 0.026352313834736494),
 (529, 0.027277236279499045),
 (530, 0.07071067811865475),
 (531, 0.05270462766947299),
 (532, 0.0),
 (533, 0.036860489038724284),
 (534, 0.044194173824159216),
 (535, 0.057353933467640436),
 (536, 0.026650089544451302),
 (537, 0.07372097807744857),
 (538, 0.0),
 (539, 0.06063390625908323),
 (540, 0.05892556509887895),
 (541, 0.04856429311786321),
 (542, 0.042257712736425826),
 (543, 0.12309149097933274),
 (544, 0.09525009525014289),
 (545, 0.029880715233359837),
 (546, 0.06933752452815364),
 (547, 0.09231861823449955),
 (548, 0.0),
 (549, 0.07819290527140303),
 (550, 0.0),
 (551, 0.04682929057908469),
 (552, 0.0),
 (553, 0.034020690871988585),
 (554, 0.031750031750047626),
 (555, 0.01733438113203841),
 (556, 0.030316953129541614),
 (557, 0.030316953129541614),
 (558, 0.0),
 (559, 0.034020690871988585),
 (560, 0.04856429311786321),
 (561, 0.03857583749052298),
 (562, 0.0),
 (563, 0.057353933467640436),
 (564, 0.03466876226407682),
 (565, 0.04811252243246881),
 (566, 0.0773565934694095),
 (567, 0.0),
 (568, 0.06063390625908323),
 (569, 0.10206207261596575),
 (570, 0.039528470752104736),
 (571, 0.022821773229381916),
 (572, 0.09053574604251852),
 (573, 0.0236227795630767),
 (574, 0.02551551815399144),
 (575, 0.029880715233359837),
 (576, 0.06063390625908323),
 (577, 0.06454972243679027),
 (578, 0.05050762722761053),
 (579, 0.03227486121839514),
 (580, 0.026352313834736494),
 (581, 0.10400628679223047),
 (582, 0.05103103630798288),
 (583, 0.13638618139749523),
 (584, 0.053300179088902604),
 (585, 0.0),
 (586, 0.04767312946227961),
 (587, 0.10910894511799618),
 (588, 0.0),
 (589, 0.05157106231293967),
 (590, 0.036860489038724284),
 (591, 0.053916386601719206),
 (592, 0.05661385170722978),
 (593, 0.0),
 (594, 0.057353933467640436),
 (595, 0.05661385170722978),
 (596, 0.10101525445522105),
 (597, 0.06063390625908323),
 (598, 0.0),
 (599, 0.017589938618257295),
 (600, 0.05050762722761053),
 (601, 0.03857583749052298),
 (602, 0.0472455591261534),
 (603, 0.06063390625908323),
 (604, 0.07372097807744857),
 (605, 0.0),
 (606, 0.0),
 (607, 0.09053574604251853),
 (608, 0.0),
 (609, 0.049999999999999996),
 (610, 0.06338656910463875),
 (611, 0.026064301757134343),
 (612, 0.07426106572325056),
 (613, 0.04055535528269063),
 (614, 0.031249999999999993),
 (615, 0.03466876226407682),
 (616, 0.03857583749052298),
 (617, 0.029061909685954818),
 (618, 0.10314212462587934),
 (619, 0.059761430466719674),
 (620, 0.0),
 (621, 0.036860489038724284),
 (622, 0.023414645289542346),
 (623, 0.04811252243246881),
 (624, 0.08574929257125441),
 (625, 0.0),
 (626, 0.03227486121839514),
 (627, 0.12166606584807188),
 (628, 0.05521576303742327),
 (629, 0.026064301757134343),
 (630, 0.026958193300859603),
 (631, 0.028676966733820218),
 (632, 0.0),
 (633, 0.049999999999999996),
 (634, 0.06063390625908323),
 (635, 0.026352313834736494),
 (636, 0.029880715233359837),
 (637, 0.0),
 (638, 0.0),
 (639, 0.031249999999999993),
 (640, 0.053916386601719206),
 (641, 0.0),
 (642, 0.032826608214930636),
 (643, 0.08385254915624211),
 (644, 0.06063390625908323),
 (645, 0.09999999999999999),
 (646, 0.058123819371909635),
 (647, 0.0),
 (648, 0.0),
 (649, 0.1178511301977579),
 (650, 0.0),
 (651, 0.02795084971874737),
 (652, 0.0),
 (653, 0.042874646285627205),
 (654, 0.07024393586862704),
 (655, 0.027277236279499045),
 (656, 0.0),
 (657, 0.05856516070822727),
 (658, 0.05590169943749474),
 (659, 0.05661385170722978),
 (660, 0.07216878364870323),
 (661, 0.06681531047810609),
 (662, 0.0),
 (663, 0.0),
 (664, 0.10206207261596575),
 (665, 0.0828236445561349),
 (666, 0.05455447255899809),
 (667, 0.0),
 (668, 0.07372097807744857),
 (669, 0.0),
 (670, 0.0),
 (671, 0.02830692585361489),
 (672, 0.030772872744833184),
 (673, 0.0),
 (674, 0.025785531156469834),
 (675, 0.053916386601719206),
 (676, 0.06933752452815364),
 (677, 0.029061909685954818),
 (678, 0.06565321642986127),
 (679, 0.0),
 (680, 0.029462782549439476),
 (681, 0.0),
 (682, 0.0),
 (683, 0.053916386601719206),
 (684, 0.0),
 (685, 0.039528470752104736),
 (686, 0.036084391824351615),
 (687, 0.06063390625908323),
 (688, 0.0),
 (689, 0.05590169943749474),
 (690, 0.030316953129541614),
 (691, 0.10606601717798213),
 (692, 0.0),
 (693, 0.0),
 (694, 0.07150969419341942),
 (695, 0.07216878364870323),
 (696, 0.045267873021259265),
 (697, 0.08838834764831843),
 (698, 0.04950737714883371),
 (699, 0.0),
 (700, 0.03227486121839514),
 (701, 0.0),
 (702, 0.05103103630798288),
 (703, 0.0),
 (704, 0.025785531156469834),
 (705, 0.026650089544451302),
 (706, 0.027277236279499045),
 (707, 0.03768891807222045),
 (708, 0.026650089544451302),
 (709, 0.04642383454426296),
 (710, 0.04682929057908469),
 (711, 0.10400628679223047),
 (712, 0.026352313834736494),
 (713, 0.0),
 (714, 0.0),
 (715, 0.11058146711617285),
 (716, 0.07372097807744857),
 (717, 0.04950737714883371),
 (718, 0.024282146558931603),
 (719, 0.041666666666666664),
 (720, 0.0),
 (721, 0.03466876226407682),
 (722, 0.024753688574416854),
 (723, 0.0),
 (724, 0.053916386601719206),
 (725, 0.0),
 (726, 0.0),
 (727, 0.03812464258315116),
 (728, 0.05270462766947299),
 (729, 0.0),
 (730, 0.08006407690254355),
 (731, 0.08603090020146065),
 (732, 0.05521576303742327),
 (733, 0.0),
 (734, 0.07905694150420949),
 (735, 0.026064301757134343),
 (736, 0.03466876226407682),
 (737, 0.05590169943749474),
 (738, 0.07715167498104596),
 (739, 0.04055535528269063),
 (740, 0.05521576303742327),
 (741, 0.06154574548966637),
 (742, 0.036084391824351615),
 (743, 0.026958193300859603),
 (744, 0.07071067811865475),
 (745, 0.09847982464479191),
 (746, 0.09095085938862485),
 (747, 0.05050762722761053),
 (748, 0.039528470752104736),
 (749, 0.0),
 (750, 0.053916386601719206),
 (751, 0.0),
 (752, 0.029462782549439476),
 (753, 0.030772872744833184),
 (754, 0.05661385170722978),

In [109]:
import pickle

In [110]:
pickle.dump(new_df, open('movies.pkl', 'wb'))

In [112]:
pickle.dump(new_df.to_dict(), open('movie_dict.pkl', 'wb'))

In [113]:
pickle.dump(similarity, open('similarity.pkl', 'wb'))